#!/bin/bash

# Iterate over all the commits in the current branch of a repo
# This script should be placed and run from outside the repo
# Usage: ./get-coverage <repo-path>
#
# repo-path:     relative path to dir of repo
#
# E.g.: ./get-coverage ./test-repo

find $1 -name 'package.json' -not -path "*node_modules*" -execdir yarn install \; -execdir yarn test --coverage --watchAll=false --coverageReporters=text-summary \;

